# Generated by Django 6.0.1 on 2026-01-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assettype_assettypefield_flexibleasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hostname',
            field=models.CharField(blank=True, help_text='Network hostname/FQDN', max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IPv4 or IPv6 address', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='mac_address',
            field=models.CharField(blank=True, help_text='MAC address (e.g., 00:11:22:33:44:55)', max_length=17),
        ),
    ]
