# Generated by Django 6.0.1 on 2026-01-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_hostname_asset_ip_address_asset_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_rackmount',
            field=models.BooleanField(default=False, help_text='Is this asset rackmountable?'),
        ),
        migrations.AddField(
            model_name='asset',
            name='rack_units',
            field=models.PositiveIntegerField(blank=True, help_text='Height in rack units (U)', null=True),
        ),
    ]
