# Generated by Django 6.0.1 on 2026-01-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_add_rackmount_fields'),
        ('core', '0008_organization_city_organization_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(help_text='Marketing/display name (e.g., PowerEdge R740)', max_length=200)),
                ('model_number', models.CharField(blank=True, help_text='Specific model/part number (e.g., R740XD)', max_length=200)),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=250, unique=True)),
                ('equipment_type', models.CharField(choices=[('server', 'Server'), ('workstation', 'Workstation'), ('laptop', 'Laptop'), ('switch', 'Network Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('access_point', 'Wireless Access Point'), ('storage', 'Storage Device'), ('ups', 'UPS'), ('pdu', 'Power Distribution Unit'), ('patch_panel', 'Patch Panel'), ('kvm', 'KVM Switch'), ('phone', 'IP Phone'), ('camera', 'IP Camera'), ('other', 'Other')], help_text='Type of equipment', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Equipment description')),
                ('is_rackmount', models.BooleanField(default=False, help_text='Whether equipment is rackmountable')),
                ('rack_units', models.PositiveIntegerField(blank=True, help_text='Height in rack units (1U, 2U, etc.)', null=True)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Equipment specifications in JSON format')),
                ('datasheet_url', models.URLField(blank=True, help_text='Link to vendor datasheet/spec sheet')),
                ('documentation_url', models.URLField(blank=True, help_text='Link to user manual/documentation')),
                ('release_date', models.DateField(blank=True, help_text='Product release date', null=True)),
                ('eol_date', models.DateField(blank=True, help_text='End of life date', null=True)),
                ('eos_date', models.DateField(blank=True, help_text='End of support date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether model is actively used/sold')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Additional model-specific metadata')),
            ],
            options={
                'db_table': 'equipment_models',
                'ordering': ['vendor__name', 'model_name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='equipment_model',
            field=models.ForeignKey(blank=True, help_text='Select equipment model from vendor database (auto-fills manufacturer/model)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.equipmentmodel'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Vendor name (e.g., Dell, HP, Cisco)', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=200, unique=True)),
                ('website', models.URLField(blank=True, help_text='Vendor website URL')),
                ('support_url', models.URLField(blank=True, help_text='Vendor support/documentation URL')),
                ('support_phone', models.CharField(blank=True, help_text='Vendor support phone number', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Brief description of vendor')),
                ('is_active', models.BooleanField(default=True, help_text='Whether vendor is actively used')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Additional vendor metadata')),
            ],
            options={
                'db_table': 'vendors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='vendors_name_a8eecc_idx'), models.Index(fields=['is_active'], name='vendors_is_acti_04b085_idx')],
            },
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='vendor',
            field=models.ForeignKey(help_text='Equipment manufacturer', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_models', to='assets.vendor'),
        ),
        migrations.CreateModel(
            name='NetworkPortConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration_name', models.CharField(help_text="Configuration name (e.g., 'Default', 'Production VLAN Setup')", max_length=200)),
                ('ports', models.JSONField(default=list, help_text='Port configuration array')),
                ('vlans', models.JSONField(blank=True, default=list, help_text='VLAN definitions')),
                ('notes', models.TextField(blank=True, help_text='Configuration notes')),
                ('is_template', models.BooleanField(default=False, help_text='Whether this is a template configuration')),
                ('asset', models.ForeignKey(blank=True, help_text='Specific asset instance (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_configurations', to='assets.asset')),
                ('equipment_model', models.ForeignKey(help_text='Equipment model this configuration is for', on_delete=django.db.models.deletion.CASCADE, related_name='port_configurations', to='assets.equipmentmodel')),
                ('organization', models.ForeignKey(help_text='Organization this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'db_table': 'network_port_configurations',
                'ordering': ['equipment_model', 'configuration_name'],
                'indexes': [models.Index(fields=['equipment_model'], name='network_por_equipme_37efd3_idx'), models.Index(fields=['asset'], name='network_por_asset_i_9b8424_idx'), models.Index(fields=['is_template'], name='network_por_is_temp_57ebf5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['vendor', 'model_name'], name='equipment_m_vendor__be0f64_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['equipment_type'], name='equipment_m_equipme_6b5580_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['is_active'], name='equipment_m_is_acti_2895dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentmodel',
            unique_together={('vendor', 'model_name')},
        ),
    ]
