# Generated by Django 6.0.1 on 2026-01-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organization_city_organization_country_and_more'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.CharField(help_text='Organization ID in source system', max_length=100)),
                ('source_name', models.CharField(help_text='Organization name in source system', max_length=255)),
                ('was_created', models.BooleanField(default=False, help_text='True if organization was created, False if matched')),
                ('match_score', models.IntegerField(blank=True, help_text='Fuzzy match score (0-100) if matched', null=True)),
            ],
            options={
                'db_table': 'organization_mappings',
            },
        ),
        migrations.AddField(
            model_name='importjob',
            name='fuzzy_match_threshold',
            field=models.IntegerField(default=85, help_text='Similarity threshold for fuzzy matching (0-100, default 85)'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='organizations_created',
            field=models.PositiveIntegerField(default=0, help_text='Number of organizations created during import'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='organizations_matched',
            field=models.PositiveIntegerField(default=0, help_text='Number of organizations matched to existing'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='use_fuzzy_matching',
            field=models.BooleanField(default=True, help_text='Use fuzzy matching to find existing organizations with similar names'),
        ),
        migrations.AddField(
            model_name='importmapping',
            name='source_organization_id',
            field=models.CharField(blank=True, help_text='Source organization ID for this object', max_length=100),
        ),
        migrations.AddField(
            model_name='importmapping',
            name='target_organization',
            field=models.ForeignKey(blank=True, help_text='Organization this object belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='target_organization',
            field=models.ForeignKey(blank=True, help_text='Optional: Import into specific organization. Leave blank to import all organizations from source.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='importmapping',
            index=models.Index(fields=['source_organization_id'], name='import_mapp_source__88b18d_idx'),
        ),
        migrations.AddField(
            model_name='organizationmapping',
            name='import_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_mappings', to='imports.importjob'),
        ),
        migrations.AddField(
            model_name='organizationmapping',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_mappings', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='organizationmapping',
            index=models.Index(fields=['source_id'], name='organizatio_source__fbb20f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmapping',
            index=models.Index(fields=['organization'], name='organizatio_organiz_ac8c56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmapping',
            unique_together={('import_job', 'source_id')},
        ),
    ]
