# Generated by Django 6.0.1 on 2026-01-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_organizationmapping_importjob_fuzzy_match_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='floor_plans_imported',
            field=models.PositiveIntegerField(default=0, help_text='Number of floor plans imported (MagicPlan)'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='import_floor_plans',
            field=models.BooleanField(default=True, help_text='Import floor plans (MagicPlan only)'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='source_file',
            field=models.FileField(blank=True, help_text='MagicPlan JSON export file', null=True, upload_to='imports/magicplan/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='source_api_key',
            field=models.CharField(blank=True, help_text='API key for authentication - not needed for MagicPlan', max_length=500),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='source_type',
            field=models.CharField(choices=[('itglue', 'IT Glue'), ('hudu', 'Hudu'), ('magicplan', 'MagicPlan Floor Plans')], max_length=20),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='source_url',
            field=models.URLField(blank=True, help_text='API endpoint URL (e.g., https://api.itglue.com or https://demo.hudu.com) - not needed for MagicPlan'),
        ),
    ]
