# Generated by Django 6.0.1 on 2026-01-10 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_asset_hostname_asset_ip_address_asset_mac_address'),
        ('core', '0006_systemsetting_azure_ad_auto_create_users_and_more'),
        ('docs', '0004_diagram_diagramannotation_diagramversion_and_more'),
        ('vault', '0005_password_database_host_password_database_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False, help_text='Global process - visible to all organizations')),
                ('is_published', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False, help_text='Process template - can be cloned by organizations')),
                ('category', models.CharField(choices=[('onboarding', 'User Onboarding'), ('offboarding', 'User Offboarding'), ('deployment', 'System Deployment'), ('maintenance', 'Maintenance'), ('incident', 'Incident Response'), ('backup', 'Backup/Recovery'), ('security', 'Security Audit'), ('change', 'Change Management'), ('other', 'Other')], default='other', max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes_modified', to=settings.AUTH_USER_MODEL)),
                ('linked_diagram', models.ForeignKey(blank=True, help_text='Link to a diagram for visual representation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='docs.diagram')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='core.organization')),
                ('tags', models.ManyToManyField(blank=True, related_name='processes', to='core.tag')),
            ],
            options={
                'db_table': 'processes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProcessExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_process_executions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_executions', to='core.organization')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='processes.process')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_process_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'process_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed instructions for this stage')),
                ('requires_confirmation', models.BooleanField(default=False, help_text='Stage requires user to confirm completion')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated time to complete (minutes)', null=True)),
                ('linked_asset', models.ForeignKey(blank=True, help_text='Related asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_stages', to='assets.asset')),
                ('linked_document', models.ForeignKey(blank=True, help_text='Related knowledge base document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_stages', to='docs.document')),
                ('linked_password', models.ForeignKey(blank=True, help_text='Related password/credential', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_stages', to='vault.password')),
                ('linked_secure_note', models.ForeignKey(blank=True, help_text='Related secure note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_stages', to='core.securenote')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='processes.process')),
            ],
            options={
                'db_table': 'process_stages',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStageCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_completions', to='processes.processexecution')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='processes.processstage')),
            ],
            options={
                'db_table': 'process_stage_completions',
                'ordering': ['stage__order'],
            },
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['organization', 'slug'], name='processes_organiz_ac1971_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['is_global', 'is_published'], name='processes_is_glob_513bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['category'], name='processes_categor_60cdd9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='processexecution',
            index=models.Index(fields=['organization', '-created_at'], name='process_exe_organiz_7b437c_idx'),
        ),
        migrations.AddIndex(
            model_name='processexecution',
            index=models.Index(fields=['assigned_to', 'status'], name='process_exe_assigne_126eae_idx'),
        ),
        migrations.AddIndex(
            model_name='processexecution',
            index=models.Index(fields=['process', 'status'], name='process_exe_process_f024c9_idx'),
        ),
        migrations.AddIndex(
            model_name='processstage',
            index=models.Index(fields=['process', 'order'], name='process_sta_process_315961_idx'),
        ),
        migrations.AddIndex(
            model_name='processstagecompletion',
            index=models.Index(fields=['execution', 'is_completed'], name='process_sta_executi_1255a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processstagecompletion',
            unique_together={('execution', 'stage')},
        ),
    ]
