# Generated by Django 6.0.1 on 2026-01-10 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemsetting_azure_ad_auto_create_users_and_more'),
        ('docs', '0003_document_is_global'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('diagram_xml', models.TextField(help_text='.drawio XML format')),
                ('png_export', models.FileField(blank=True, help_text='PNG export of diagram', null=True, upload_to='diagrams/png/')),
                ('svg_export', models.FileField(blank=True, help_text='SVG export of diagram', null=True, upload_to='diagrams/svg/')),
                ('diagram_type', models.CharField(choices=[('network', 'Network Diagram'), ('process', 'Process Flow'), ('architecture', 'System Architecture'), ('rack', 'Rack Layout'), ('floorplan', 'Floor Plan'), ('org', 'Organizational Chart'), ('erd', 'Entity Relationship Diagram'), ('flowchart', 'Flowchart'), ('other', 'Other')], default='other', max_length=50)),
                ('is_global', models.BooleanField(default=False, help_text='Global diagram - visible to all organizations')),
                ('is_published', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(default=False, help_text='Diagram template - can be cloned')),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagrams_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagrams_modified', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='core.organization')),
                ('tags', models.ManyToManyField(blank=True, related_name='diagrams', to='core.tag')),
            ],
            options={
                'db_table': 'diagrams',
                'ordering': ['-last_edited_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagramAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('annotation_type', models.CharField(choices=[('note', 'Note'), ('comment', 'Comment'), ('issue', 'Issue'), ('suggestion', 'Suggestion')], default='note', max_length=20)),
                ('position_x', models.IntegerField(blank=True, null=True)),
                ('position_y', models.IntegerField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagram_annotations', to=settings.AUTH_USER_MODEL)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='docs.diagram')),
            ],
            options={
                'db_table': 'diagram_annotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagramVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('diagram_xml', models.TextField(help_text='Snapshot of diagram XML')),
                ('change_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='docs.diagram')),
            ],
            options={
                'db_table': 'diagram_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='diagram',
            index=models.Index(fields=['organization', 'slug'], name='diagrams_organiz_1a1b80_idx'),
        ),
        migrations.AddIndex(
            model_name='diagram',
            index=models.Index(fields=['diagram_type'], name='diagrams_diagram_cd6a16_idx'),
        ),
        migrations.AddIndex(
            model_name='diagram',
            index=models.Index(fields=['is_global', 'is_published'], name='diagrams_is_glob_3d8038_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diagram',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='diagramannotation',
            index=models.Index(fields=['diagram', '-created_at'], name='diagram_ann_diagram_555caa_idx'),
        ),
        migrations.AddIndex(
            model_name='diagramversion',
            index=models.Index(fields=['diagram', '-version_number'], name='diagram_ver_diagram_d811a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diagramversion',
            unique_together={('diagram', 'version_number')},
        ),
    ]
