# Generated by Django 6.0.1 on 2026-01-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_diagram_diagramannotation_diagramversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail preview (300x200)', null=True, upload_to='diagrams/thumbnails/'),
        ),
    ]
