# Generated by Django 6.0.1 on 2026-01-10 18:15

from django.db import migrations
from django.core.management import call_command


def seed_templates(apps, schema_editor):
    """Seed initial document and diagram templates on fresh installs"""
    Document = apps.get_model('docs', 'Document')
    Diagram = apps.get_model('docs', 'Diagram')

    # Only seed if there are no templates yet (fresh install)
    if not Document.objects.filter(is_template=True).exists():
        # Use the management commands to seed templates
        try:
            call_command('seed_templates')
            print("✓ Seeded document templates")
        except Exception as e:
            print(f"! Could not seed document templates: {e}")

    if not Diagram.objects.filter(is_template=True).exists():
        try:
            call_command('seed_diagram_templates')
            print("✓ Seeded diagram templates")
        except Exception as e:
            print(f"! Could not seed diagram templates: {e}")


def reverse_seed(apps, schema_editor):
    """Optional: Remove templates on migration rollback"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_add_diagram_thumbnail'),
    ]

    operations = [
        migrations.RunPython(seed_templates, reverse_seed),
    ]
