# Generated by Django 6.0.1 on 2026-01-10 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemsetting_azure_ad_auto_create_users_and_more'),
        ('docs', '0008_make_organization_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization for org-specific diagrams. NULL for global diagram templates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='core.organization'),
        ),
    ]
