# Generated by Django 6.0.1 on 2026-01-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_add_rmm_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psaconnection',
            name='provider_type',
            field=models.CharField(choices=[('connectwise_manage', 'ConnectWise Manage'), ('autotask', 'Autotask PSA'), ('halo_psa', 'HaloPSA'), ('kaseya_bms', 'Kaseya BMS'), ('syncro', 'Syncro'), ('freshservice', 'Freshservice'), ('zendesk', 'Zendesk'), ('itflow', 'ITFlow')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rmmconnection',
            name='provider_type',
            field=models.CharField(choices=[('ninjaone', 'NinjaOne'), ('datto_rmm', 'Datto RMM'), ('connectwise_automate', 'ConnectWise Automate'), ('atera', 'Atera'), ('tactical_rmm', 'Tactical RMM')], max_length=50),
        ),
    ]
