# Generated by Django 6.0.1 on 2026-01-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='entity_type',
            field=models.CharField(choices=[('asset', 'Asset'), ('document', 'Document'), ('password', 'Password'), ('contact', 'Contact'), ('vendor', 'Vendor'), ('equipment_model', 'Equipment Model')], max_length=50),
        ),
    ]
