# Generated by Django 6.0.1 on 2026-01-10 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_hostname_asset_ip_address_asset_mac_address'),
        ('monitoring', '0003_websitemonitor_ssl_issued_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='rackdevice',
            name='asset_id',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Link to Asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='rackdevice',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Link to Asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_devices', to='assets.asset'),
        ),
    ]
