# Generated by Django 6.0.1 on 2026-01-11 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_equipmentmodel_asset_equipment_model_vendor_and_more'),
        ('monitoring', '0005_rack_ambient_temp_f_rack_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rackdevice',
            name='equipment_model',
            field=models.ForeignKey(blank=True, help_text='Equipment model from vendor database', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_devices', to='assets.equipmentmodel'),
        ),
    ]
