# Generated by Django 6.0.1 on 2026-01-12 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_scheduledtask_task_type'),
        ('monitoring', '0007_add_patch_panel_port_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rackresource',
            name='port_configuration',
        ),
        migrations.RemoveField(
            model_name='rackresource',
            name='rack_units',
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='vlan_id',
        ),
        migrations.RemoveField(
            model_name='subnet',
            name='vlan_name',
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vlan_id', models.PositiveIntegerField(help_text='VLAN number (1-4094)')),
                ('name', models.CharField(help_text='VLAN name (e.g., Production, Guest, DMZ)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='Hex color code (e.g., #FF5733)', max_length=7)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlans', to='core.organization')),
            ],
            options={
                'db_table': 'vlans',
                'ordering': ['vlan_id'],
            },
        ),
        migrations.AddField(
            model_name='subnet',
            name='vlan',
            field=models.ForeignKey(blank=True, help_text='Associated VLAN', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnets', to='monitoring.vlan'),
        ),
        migrations.AddIndex(
            model_name='vlan',
            index=models.Index(fields=['organization', 'vlan_id'], name='vlans_organiz_2a82bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together={('organization', 'vlan_id')},
        ),
    ]
