# Generated by Django 6.0.1 on 2026-01-11 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_password_database_host_password_database_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordBreachCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('is_breached', models.BooleanField(default=False)),
                ('breach_count', models.PositiveIntegerField(default=0, help_text='Number of times password found in breaches')),
                ('breach_source', models.CharField(default='haveibeenpwned', help_text='Source of breach data', max_length=50)),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breach_checks', to='vault.password')),
            ],
            options={
                'db_table': 'password_breach_checks',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['password', '-checked_at'], name='password_br_passwor_721c30_idx'), models.Index(fields=['is_breached'], name='password_br_is_brea_383a70_idx')],
            },
        ),
    ]
