# Generated by Django 6.0.1 on 2026-01-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_add_password_breach_checking'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Additional custom data (e.g., breach scan frequency)'),
        ),
    ]
