# Generated by Django 6.0.1 on 2026-01-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_add_custom_fields_to_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='strength_score',
            field=models.IntegerField(default=0, help_text='Password strength score (0=weak, 100=strong)'),
        ),
    ]
