# Generated by Django 6.0.1 on 2026-01-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationfloorplan',
            name='source',
            field=models.CharField(choices=[('tax_record', 'Tax/Property Record'), ('satellite', 'Satellite Imagery Analysis'), ('building_footprint', 'Building Footprint Data'), ('user_input', 'User Provided'), ('ai_estimate', 'AI Estimation'), ('magicplan', 'MagicPlan Import'), ('hybrid', 'Multiple Sources')], default='ai_estimate', help_text='Primary data source for dimensions', max_length=20),
        ),
    ]
